# For selenium
TICKER = 'ticker'
PRICE = 'price'
HIGH_LOW = 'high_low'
HIGH = 'high'
LOW = 'low'
STOCK_PE = 'stockPE'
INDUSTRY_PE = 'industryPE'
INTRINSIC_VALUE = 'intrinsicValue'
GRAHAM_NUMBER = 'grahamNumber'
CFO = 'cfo'
PAT = 'pat'
ROCE = 'roce'
ROE = 'roe'

# For bs4
QUARTERS = 'quarters'
Q_SALES = 'q_sales'
Q_EXPENSES = 'q_expenses'
Q_OPM = 'q_opm'
Q_OPM_PERCENT = 'q_opm_percent'
Q_OTHER_INCOME = 'q_other_income'
Q_INTEREST = 'q_interest'
Q_DEPRECIATION = 'q_depreciation'
Q_PBT = 'q_pbt'
Q_TAX = 'q_tax'
Q_PAT = 'q_pat'
Q_EPS = 'q_eps'
Q_PDF = 'q_pdf'

Q_SALES_PERCENT = 'q_sales_percent'
Q_EXPENSES_PERCENT = 'q_expenses_percent'
Q_PAT_PERCENT = 'q_pat_percent'


YEARS = 'years'
A_SALES = 'a_sales'
A_EXPENSES = 'a_expenses'
A_OPM = 'a_opm'
A_OPM_PERCENT = 'a_opm_percent'
A_OTHER_INCOME = 'a_other_income'
A_INTEREST = 'a_interest'
A_DEPRECIATION = 'a_depreciation'
A_PBT = 'a_pbt'
A_TAX = 'a_tax'
A_PAT = 'a_pat'
A_EPS = 'a_eps'
A_PDF = 'a_pdf'

A_SALES_PERCENT = 'a_sales_percent'
A_EXPENSES_PERCENT = 'a_expenses_percent'
A_PAT_PERCENT = 'a_pat_percent'
